# start profiling in ZSH
if [[ "$ZPROF" = true ]]; then
  zmodload zsh/zprof
fi

# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && . "$HOME/.fig/shell/zshrc.pre.zsh"

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && . "$HOME/.fig/shell/zshrc.post.zsh"

# stop ZSH profiling and print profiling information
if [[ "$ZPROF" = true ]]; then
  zprof
fi
