# frozen_string_literal: true

source 'https://rubygems.org'

gem 'serverspec', '= 2.41.5'

gem 'pry-doc', '= 1.1.0'
gem 'pry-alias', '= 0.0.1'
gem 'pry-nav', '= 0.3.0'
gem 'pry-remote', '= 0.1.8'
gem 'pry-stack_explorer', '= 0.4.9.3'
