#!/usr/bin/env bats

# Devcontainer Builder Tests
# These tests validate the devcontainer-builder image functionality

setup() {
  TEST_DIR="$(cd "$(dirname "${BATS_TEST_FILENAME}")" && pwd)"
  PROJECT_DIR="$(dirname "${TEST_DIR}")"

  # Read image reference from dist/image.json (generated by build target)
  IMAGE_JSON="${PROJECT_DIR}/dist/image.json"
  if [ ! -f "${IMAGE_JSON}" ]; then
    echo "Error: ${IMAGE_JSON} not found. Run 'moon run devcontainer-builder:build' first." >&2
    exit 1
  fi

  # Extract image reference from JSON using jq or grep/sed fallback
  if command -v jq &>/dev/null; then
    IMAGE_NAME=$(jq -r '.image' "${IMAGE_JSON}")
  else
    IMAGE_NAME=$(grep -o '"image"[[:space:]]*:[[:space:]]*"[^"]*"' "${IMAGE_JSON}" | sed 's/.*"image"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  fi

  if [ -z "${IMAGE_NAME}" ]; then
    echo "Error: Could not extract image name from ${IMAGE_JSON}" >&2
    exit 1
  fi
}

# =============================================================================
# CLI Tool Tests
# Note: Using --entrypoint to bypass docker-init.sh which requires privileged mode
# =============================================================================

@test "git is available" {
  run docker run --rm --entrypoint git "${IMAGE_NAME}" --version
  [ "$status" -eq 0 ]
  [[ "$output" =~ "git version" ]]
}

@test "python is available" {
  run docker run --rm --entrypoint python "${IMAGE_NAME}" --version
  [ "$status" -eq 0 ]
  [[ "$output" =~ "Python 3" ]]
}

@test "nodejs is available" {
  run docker run --rm --entrypoint node "${IMAGE_NAME}" --version
  [ "$status" -eq 0 ]
  [[ "$output" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]
}
