# ArgoCD ApplicationSet configuration for Manifests
appType: infra
appName: manifests
platform: secrets-proxy
namespace: tenant-prod-secretsproxy

cluster: enigma
createNamespace: false
prUpdateNamespace: true
prUpdateCluster: false

prOverrides: {}
