apiVersion: v2
name: argocd-cluster-registration
description: Umbrella chart for ArgoCD cluster registration Kyverno policies
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: argocd-cluster-registration
    version: 0.1.0
    repository: file://../../../libs/argocd-cluster-registration
