# frozen_string_literal: true

source 'https://rubygems.org'

gem 'inspec-bin', '= 5.12.2'
gem 'test-kitchen', '= 3.2.2'
gem 'kitchen-inspec', '= 2.5.2'
gem 'kitchen-vagrant', '= 1.11.0'

# gem 'pry-doc', '= 1.1.0'
# gem 'pry-alias', '= 0.0.1'
# gem 'pry-nav', '= 0.3.0'
# gem 'pry-remote', '= 0.1.8'
# gem 'pry-stack_explorer', '= 0.4.9.3'
