# ArgoCD ApplicationSet configuration for Tenant
appType: tenant
appName: tenant
platform: argocd
namespace: tenant-prod

cluster: enigma
createNamespace: false
prUpdateNamespace: false
prUpdateCluster: false

prOverrides: {}
