apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tenant-secrets-proxy.yaml
  # TODO: Add back after fixing JMESPath syntax for hyphenated keys
  # - clusterpolicy-argocd-cluster-registration.yaml
  - ciliumnetworkpolicy-allow-to-root-ingress.yaml
