apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-apps-helm
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - pullRequest:
              github:
                owner: vgijssel
                repo: setup
                labels:
                  - apps:secrets-proxy
                tokenRef:
                  secretName: github-token
                  key: token
              requeueAfterSeconds: 1800
          - selector:
              matchExpressions:
                - key: helm
                  operator: In
                  values:
                    - "true"
            git:
              repoURL: https://github.com/vgijssel/setup.git
              revision: "{{.head_sha}}"
              files:
                - path: apps/secrets-proxy/*/config.json
                - path: apps/secrets-proxy-infra/*/config.json
  template:
    metadata:
      name: "{{index .path.segments 1}}-{{index .path.segments 2}}-pr-{{.number}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/vgijssel/setup.git
        targetRevision: "{{.head_sha}}"
        path: "{{.path.path}}"
        helm:
          valueFiles:
            - values.yaml
          parameters:
            - name: prNumber
              value: "{{.number}}"
            - name: tenant.prNumber
              value: "{{.number}}"
      destination:
        name: "{{.cluster}}-pr-{{.number}}"
        namespace: "{{.namespace}}-pr-{{.number}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
      info:
        - name: PR
          value: "https://github.com/vgijssel/setup/pull/{{.number}}"
        - name: Branch
          value: "{{.branch}}"
