apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-helm
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - selector:
        matchExpressions:
          - key: helm
            operator: In
            values:
              - "true"
      git:
        repoURL: https://github.com/vgijssel/setup.git
        revision: mg/chore/refactor-argocd-directory-structure
        files:
          - path: apps/*/*/config.json
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 2}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/vgijssel/setup.git
        targetRevision: mg/chore/refactor-argocd-directory-structure
        path: '{{.path.path}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        name: '{{.cluster}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-manifests
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - selector:
        matchExpressions:
          - key: helm
            operator: In
            values:
              - "false"
      git:
        repoURL: https://github.com/vgijssel/setup.git
        revision: mg/chore/refactor-argocd-directory-structure
        files:
          - path: apps/*/*/config.json
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 2}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/vgijssel/setup.git
        targetRevision: mg/chore/refactor-argocd-directory-structure
        path: '{{.path.path}}'
      destination:
        name: '{{.cluster}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
