apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applicationset-helm.yaml
  - applicationset-manifests.yaml
  - applicationset-pr-helm.yaml
  - applicationset-pr-manifests.yaml
