# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure('2') do |config|
  config.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.define "razor-server", primary: true do |razor|
    razor.vm.box = 'file://razor-server.box'

    razor.vm.synced_folder "../deploy-image/images/deploy-image", "/repo/deploy-image"
    razor.vm.synced_folder "../libvirt/images/libvirt", "/repo/libvirt"
    razor.vm.synced_folder "./elements/razor-server/static/tasks/deploy-image.task", "/tasks/deploy-image.task"
    razor.vm.synced_folder "../ipxe", "/tftpboot/ipxe"

    razor.vm.hostname = 'razor-server'

    razor.vm.provider 'virtualbox' do |vb|
      vb.gui = false
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--uart1", "0x3f8", "4"]
      vb.customize ["modifyvm", :id, "--uartmode1", "file", "/tmp/razor-server.log"]
    end
  end

  config.vm.define "pxe", autostart: false do |pxe|
    pxe.vm.box = 'file://empty.box'
    pxe.vm.graceful_halt_timeout = 0

    pxe.vm.provider 'virtualbox' do |vb|
      # Make sure the bridged network adapter is used for PXE
      # 0 is the lowest priority, 1 is the highest priority
      vb.customize ["modifyvm", :id, "--nicbootprio1", "0"]
      vb.customize ["modifyvm", :id, "--nicbootprio2", "1"]

      vb.gui = false

      # We need a lot of memory here because a disk is downloaded and extracted into ram
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--uart1", "0x3f8", "4"]
      vb.customize ["modifyvm", :id, "--uartmode1", "file", "/tmp/pxe.log"]
    end
  end
end
