appType: apps
appName: coredns-patch
platform: cluster-networking
namespace: cluster-networking

cluster: enigma
createNamespace: true
prUpdateNamespace: true
prUpdateCluster: false
serverSideApply: true

prOverrides: {}
