appType: apps
appName: onepassword-operator
platform: secrets-proxy
namespace: default

cluster: secrets-proxy-vcluster
createNamespace: true
prUpdateNamespace: false
prUpdateCluster: true

prOverrides: {}
