apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/vgijssel/setup
    targetRevision: mg/feat/deploy-secrets-proxy
    path: third_party/vendir/charts/1password-connect
    helm:
      values: |
        operator:
          create: true
          watchNamespace: []
          token:
            name: 1password-operator-token
            key: token
        connect:
          create: true
          credentialsName: 1password-credentials
          credentialsKey: 1password-credentials.json
  destination:
    name: secrets-proxy
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
