apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-secrets.yaml
  - application-1password-operator.yaml
  - application-1password-secrets.yaml
  - application-docs-sync-b2-proxy.yaml
