apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../../third_party/vendir/manifests/argocd/ha
  - ingress-http.yaml
  - ingress-grpc.yaml
  - ingress-applicationset-webhook.yaml
  - ingress-server-webhook.yaml

patches:
  - path: patch-argocd-cmd-params-cm.yaml
