source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

# Specify your gem's dependencies in arel_toolkit.gemspec
gem 'rspec', '~> 3.9.0'
gem 'async', '~> 1.24.2'
gem 'async-process', '~> 1.2.0'
gem 'async-io', '~> 1.27.3'
gem 'pry', '~> 0.12.2'
