apiVersion: v2
name: secrets-proxy-infra-namespace
description: Namespace configuration for Secrets Proxy infrastructure
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: namespace
    version: 0.1.0
    repository: file://../../../libs/namespace
