apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-to-vcluster-dns
  namespace: tenant-prod-argocd
spec:
  description: >-
    Allow egress to vCluster's internal CoreDNS for DNS resolution.
    The vCluster CoreDNS has label k8s-app=vcluster-kube-dns.
  endpointSelector: {}
  egress:
    - toEndpoints:
        - matchLabels:
            k8s-app: vcluster-kube-dns
            k8s:io.kubernetes.pod.namespace: tenant-prod-argocd
      toPorts:
        - ports:
            - port: "1053"
              protocol: UDP
            - port: "1053"
              protocol: TCP
