apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-to-secrets-proxy
  namespace: tenant-prod-argocd
spec:
  description: >-
    Allow egress from ArgoCD vCluster to secrets-proxy vCluster.
    Required for ArgoCD to deploy applications to the secrets-proxy cluster.
  endpointSelector: {}
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: tenant-prod-secretsproxy
