apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: setup-argocd
  namespace: tenant-argocd
spec:
  interval: 5m
  url: https://github.com/vgijssel/setup
  ref:
    branch: mg/feat/restructure-enigma
