#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

cp -Ln /lib/x86_64-linux-gnu/libnss_dns.so.2 $TMP_MOUNT_PATH/lib/libnss_dns.so.2
cp -Ln /lib/x86_64-linux-gnu/libnss_files.so.2 $TMP_MOUNT_PATH/lib/libnss_files.so.2

mkdir -p $TMP_MOUNT_PATH/etc/ssl/certs
cp -vR /etc/ssl/certs/* $TMP_MOUNT_PATH/etc/ssl/certs

mkdir -p $TMP_MOUNT_PATH/etc/ca-certificates
cp -vR /etc/ca-certificates/* $TMP_MOUNT_PATH/etc/ca-certificates

mkdir -p $TMP_MOUNT_PATH/usr/share/ca-certificates
cp -vR /usr/share/ca-certificates/* $TMP_MOUNT_PATH/usr/share/ca-certificates
