"""Molecule tests for Ansible roles using testinfra."""


def test_timezone_configured(host):
    """Verify timezone is set correctly by the localisation role."""
    # The localisation.yml role sets timezone to Europe/Amsterdam
    cmd = host.run("timedatectl show --property=Timezone --value")
    if cmd.rc != 0:
        # Fallback for containers without systemd
        cmd = host.run("cat /etc/timezone")
    assert cmd.rc == 0
    assert "Amsterdam" in cmd.stdout or "Europe/Amsterdam" in cmd.stdout


def test_locale_configured(host):
    """Verify locale is generated by the localisation role."""
    # The localisation.yml role generates en_GB.UTF-8
    cmd = host.run("locale -a")
    assert cmd.rc == 0
    assert "en_GB" in cmd.stdout or "en_GB.utf8" in cmd.stdout


def test_locale_files_exist(host):
    """Verify locale configuration files exist."""
    assert host.file("/etc/default/locale").exists
    assert host.file("/etc/locale.conf").exists


def test_python_installed(host):
    """Verify Python is available."""
    python = host.package("python3")
    assert python.is_installed
