# ArgoCD ApplicationSet configuration for tenant namespace
appType: tenant
appName: tenant
platform: secrets-proxy-infra
namespace: tenant-prod
cluster: enigma
createNamespace: false
prUpdateNamespace: false
prOverrides:
  "tenant.name": "secretsproxy%s"
