# ArgoCD ApplicationSet configuration for Tenant
appType: tenant
appName: tenant
platform: secrets-proxy
namespace: tenant-prod

cluster: enigma
createNamespace: false
prUpdateNamespace: false
prUpdateCluster: false

prOverrides:
  "tenant.name": "secretsproxy%s"
# test comment
