#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo "DOWNLOADING AND INSTALLING MICROKERNEL"

mkdir -p /repo
chown razor:razor /repo

wget -O microkernel.tar http://pup.pt/razor-microkernel-latest
tar -xf microkernel.tar -C /repo
rm microkernel.tar
