#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo "SETTING UP TFTPBOOT"

mkdir -p /tftpboot

wget -O /tftpboot/undionly.kpxe http://boot.ipxe.org/undionly.kpxe
