apiVersion: v1
kind: Secret
metadata:
  name: backblaze-credentials
  namespace: relay
stringData:
  bucket: s3-docs-infra-prod
  key_id: placeholder
  application_key: placeholder
  # Cross-cluster access via Service+Endpoints pointing to secrets cluster
  endpoint: http://aws-sigv4-proxy.secrets
  region: placeholder
