# ArgoCD ApplicationSet configuration for vCluster
appType: infra
appName: vcluster
platform: secrets-proxy-infra
namespace: tenant-prod-secretsproxy
cluster: enigma
createNamespace: false
prUpdateNamespace: true
prOverrides:
  "tenant.name": "secretsproxy%s"
  "vcluster.controlPlane.ingress.host": "api-secrets-proxy-infra-vcluster%s.enigma.vgijssel.nl"
