#!/usr/bin/env bash
set -Eeou pipefail

ESPHOME_FILES=$1
WORKSPACE_DIRECTORY=$BUILD_WORKSPACE_DIRECTORY
TARGET_DIRECTORY=$WORKSPACE_DIRECTORY/esphome_nimble

chmod -R 0755 $TARGET_DIRECTORY
cp -vfR $ESPHOME_FILES/. $TARGET_DIRECTORY