apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: relay-personal
  namespace: cozy-fluxcd
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: libs/relay-server
      sourceRef:
        kind: GitRepository
        name: setup
        namespace: cozy-fluxcd
      interval: 12h
      reconcileStrategy: Revision
  targetNamespace: relay
  dependsOn:
    - name: 1password-secrets
  install:
    createNamespace: true
    replace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: backblaze-credentials
      valuesKey: key_id
      targetPath: backblaze.keyId
    - kind: Secret
      name: backblaze-credentials
      valuesKey: application_key
      targetPath: backblaze.applicationKey
  values:
    name: relay-personal
    replicaCount: 1
    image:
      repository: docker.system3.md/relay-server
      tag: v0.9.2
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 40m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    logging:
      level: info
      format: pretty
    backblaze:
      bucket: docs-infra-prod
    env:
      relayServerUrl: https://personal.relay.enigma.vgijssel.nl
