#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

mkdir /curtin

# Symlink all grub-* binaries to grub2-* as curtin expects these to exist
for f in /usr/sbin/grub-*
do
    GRUB2_FILE=$(echo "${f/grub/grub2}")
    ln -fsv "$f" "$GRUB2_FILE"
done

ln -fsv /boot/grub /boot/grub2
