apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: setup-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vgijssel/setup
    targetRevision: HEAD
    path: apps/argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: setup-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
