apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace-argocd.yaml
  - ../../third_party/vendir/manifests/argo-cd/ha
  - ingress-argocd.yaml
  - application-argocd.yaml
