subinclude("//build_helpers/defs:docker")

docker_build(
    name = "digitalrebar",
    srcs = [
        "./base",
        "./scripts",
    ],
    dockerfile = "Dockerfile",
    visibility = ["PUBLIC"],
)