#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# https://superuser.com/a/684296
iptables -t nat -A POSTROUTING -s 192.168.3.0/24 -j MASQUERADE

# Save the iptables https://help.ubuntu.com/community/IptablesHowTo
# to have them loaded by iptables-persistent
iptables-save > /etc/iptables/rules.v4
