#!/usr/bin/expect -f

# Wait upto 5 minutes per statement
set timeout 300

# Prints debug information to specified file
# without this running expect scripts seem to stop at random with "spawn id exp6 not open"
exp_internal -f $::env(SETUP_TMP_DIR)/kubernetes_tests.log 0

# Start the kubernetes worker vm
spawn qemu_run.sh worker-test $::env(SETUP_KUBERNETES_DIR)/images/kubernetes_buster.qcow2

# Press ENTER in the grub boot menu
expect "GNU GRUB"
send "\n"

expect -ex "worker-test login: "
send "debian\n"

expect -ex "Password: "
send "debian\n"

# Check for the prompt
expect -ex "debian@worker-test:~$"

# Run the goss validator
send "goss --gossfile /etc/goss/goss.yaml validate\n"

# expect eof
expect "Count: 31"

close $spawn_id
