#!/usr/bin/expect -f

# Wait enough (forever) until a long-time boot
# set timeout -1
# Wait upto 10 minutes
set timeout 600

# Print debug information
exp_internal 1

# Start the guest VM
# spawn qemu-system-x86_64 -serial stdio wheezy.qcow2
spawn ./boot_qemu.sh images/kubernetes_stretch.qcow2

expect "myhost login: "
send "debian\n"

expect "Password: "
send "debian\n"

expect "debian@myhost:~\$"
send "goss --gossfile /etc/goss/goss.yaml validate\n"

expect "debian@myhost:~$"
send "shutdown -h now\n"
