#!/usr/bin/expect -f

# TODO: can we write the test output to a different serial port? Including exit status?

# each operation takes up to 300 seconds
set timeout 300

# Prints debug information to specified file
# without this running expect scripts seem to stop at random with "spawn id exp6 not open"
exp_internal -f $::env(SETUP_TMP_DIR)/kubernetes_tests.log 0

# Start the kubernetes worker vm
spawn qemu_run.sh worker-test $::env(SETUP_KUBERNETES_DIR)/images/kubernetes_buster.qcow2

# Press ENTER in the grub boot menu
expect "GNU GRUB"
send "\n"

# Wait for cloud-init to finish to not get mixed stdout messages
expect -ex "Cloud-init v. 18.3 finished at"
send "\n\n\n"

expect -ex "worker-test login: "
send "debian\n"

expect -ex "Password: "
send "debian\n"

# Check for the prompt
expect -ex "debian@worker-test:~$"

# Change to root
send "sudo su\n"
expect -ex "root@worker-test:/home/debian#"

# Run the goss validator
send "goss --gossfile /etc/goss/goss.yaml --vars <(facter -j) validate\n"

# expect eof
expect "Count: 30"

close $spawn_id
