{{- if .Values.customIngress.enabled }}
{{- $host := .Values.vcluster.controlPlane.ingress.host }}
{{- if .Values.prNumber }}
{{- $host = printf "api-pr-%s-secrets-proxy-infra-vcluster.enigma.vgijssel.nl" .Values.prNumber }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.vcluster.controlPlane.ingress.spec.ingressClassName }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: https
            path: /
            pathType: ImplementationSpecific
  tls: []
{{- end }}
