appType: apps
appName: ingress
platform: argocd
namespace: argocd

cluster: argocd-vcluster
createNamespace: true
prUpdateNamespace: false
prUpdateCluster: true
serverSideApply: false

prOverrides:
  "ingress-http.host": "argocd-%s.enigma.vgijssel.nl"
  "ingress-grpc.host": "argocd-grpc-%s.enigma.vgijssel.nl"
  "ingress-webhook.host": "argocd-webhook-public-%s.enigma.vgijssel.nl"
  "ingress-applicationset-webhook.host": "argocd-applicationset-webhook-public-%s.enigma.vgijssel.nl"
