ingress-http:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

ingress-webhook:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

ingress-grpc:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

ingress-applicationset-webhook:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
