vcluster:
  sync:
    toHost:
      ingresses:
        enabled: true
    fromHost:
      secrets:
        enabled: true
        mappings:
          byName:
            # Sync all secrets from setup-argocd-secrets namespace to argocd namespace
            setup-argocd-secrets/*: argocd/*
  controlPlane:
    statefulSet:
      highAvailability:
        replicas: 1
      pods:
        labels:
          policy.cozystack.io/allow-to-apiserver: "true"
    backingStore:
      etcd:
        deploy:
          enabled: true
          statefulSet:
            highAvailability:
              replicas: 1
            pods:
              labels:
                policy.cozystack.io/allow-to-apiserver: "true"
    ingress:
      enabled: false
