# ArgoCD ApplicationSet configuration for S3 docs proxy
appType: apps
appName: s3-docs-infra-prod-proxy-b2
platform: secrets-proxy
namespace: secrets
cluster: secrets-proxy-infra-vcluster
createNamespace: true
prUpdateNamespace: false
prUpdateCluster: true
