appType: apps
appName: s3-docs-infra-prod-proxy-b2
platform: secrets-proxy
namespace: secrets

cluster: secrets-proxy-vcluster
createNamespace: true
prUpdateNamespace: false
prUpdateCluster: true

prOverrides: {}
