#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

MACHINE_DIR="$TMP_BUILD_DIR/built"
MACHINE_NAME="image_build"

function cleanup {
    machinectl poweroff "$MACHINE_NAME"
}

trap cleanup EXIT HUP INT QUIT PIPE TERM


# Copy the digital rebar base content packs to /drp inside the image
cp -vR "$SETUP_DIGITAL_REBAR_DIR/base" "$MACHINE_DIR/drp"

systemd-run systemd-nspawn --machine="$MACHINE_NAME" -b -D "$MACHINE_DIR"

# The machine needs a fraction of time to start so it not available immediately
sleep 2

systemd-run --pty --machine "$MACHINE_NAME" --wait /drp/full_install.sh
