alias ll='ls -lah'
alias edit='code'

test -f $HOME/.cache/trunk/shell-hooks/zsh.rc && source $HOME/.cache/trunk/shell-hooks/zsh.rc;
eval "$(zoxide init zsh)"
eval "$(direnv hook zsh)"

# Generated by Hermit; START; DO NOT EDIT.
HERMIT_ROOT_BIN="${HERMIT_ROOT_BIN:-"$HOME/bin/hermit"}"
eval "$(test -x $HERMIT_ROOT_BIN && $HERMIT_ROOT_BIN shell-hooks --print --zsh)"
# Generated by Hermit; END; DO NOT EDIT.
