apiVersion: k3k.io/v1beta1
kind: Cluster
metadata:
  name: secrets
  namespace: tenant-prod
spec:
  servers: 1
  agents: 0
  version: v1.34.4-k3s1
  mode: shared
  expose:
    nodePort: {}
  persistence:
    type: dynamic
    storageRequestSize: 2G
  sync:
    secrets:
      enabled: true
    configMaps:
      enabled: true
    services:
      enabled: true
    persistentVolumeClaims:
      enabled: true
    ingresses:
      enabled: false
    priorityClasses:
      enabled: false
