---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-1password-credentials
  namespace: tenant-prod
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: tenant-prod-store
      kind: SecretStore
  selector:
    secret:
      name: 1password-credentials
  # Push all keys from source secret to remote secret with same name
  data:
    - match:
        secretKey: ""
        remoteRef:
          remoteKey: 1password-credentials
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-1password-operator-token
  namespace: tenant-prod
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: tenant-prod-store
      kind: SecretStore
  selector:
    secret:
      name: 1password-operator-token
  # Push all keys from source secret to remote secret with same name
  data:
    - match:
        secretKey: ""
        remoteRef:
          remoteKey: 1password-operator-token
