apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: tenant-prod-store
  namespace: tenant-prod
spec:
  provider:
    kubernetes:
      remoteNamespace: default
      authRef:
        name: k3k-secrets-kubeconfig
        key: kubeconfig.yaml
