substitutions:
  device_name: bathroom-shelly
  entity_id: bathroom_shelly

packages:
  device_base: !include .shelly-1l.yaml
  base: !include .base.yaml

binary_sensor:
  - <<: !include .basic_light_binary_sensor.yaml
    name: ${entity_id}_input_1
    pin: GPIO4
  - <<: !include .basic_light_binary_sensor.yaml
    name: ${entity_id}_input_2
    pin: GPIO14
