# frozen_string_literal: true

# TODO: provided by Bazel
box_dir = ENV.fetch('SETUP_BOX_DIR')
log_dir = ENV.fetch('SETUP_LOG_DIR')
provisioner_box_path = File.join(box_dir, 'provisioner.box')
provisioner_dir = ENV.fetch('SETUP_PROVISIONER_DIR')

# TODO: provided by Vault
private_key_path = ENV.fetch('PRIVATE_KEY_PATH')

Vagrant.configure('2') do |config|
  config.vm.define "provisioner" do |provisioner|
    # provisioner.vm.network "public_network", adapter: 1, auto_config: false, bridge: local_network_bridge_interface
    provisioner.vm.box = "file://#{provisioner_box_path}"
    provisioner.vm.synced_folder '.', '/vagrant', disabled: true
    provisioner.vm.network "forwarded_port", guest: 8091, host: 8091
    provisioner.vm.network "forwarded_port", guest: 8092, host: 8092

    provisioner.ssh.username = 'ubuntu'
    provisioner.ssh.private_key_path = private_key_path
    # provisioner.ssh.host = provisioner_fqdn

    provisioner.vm.cloud_init :user_data, content_type: "text/cloud-config", path: File.join(provisioner_dir, "cloud-init/dev/user-data")

    provisioner.vm.provider 'virtualbox' do |vb|
      vb.gui = false
      vb.memory = "4096"
      vb.cpus = 2

      # Enable promiscious mode on the network adapter to enable bridge networking in the vm
      vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all"]

      # Setup log file
      vb.customize ["modifyvm", :id, "--uartmode1", "file", File.join(log_dir, "provisioner.log")]
    end
  end
end
