# frozen_string_literal: true

# To install pry into the vagrant embedded gems:
# cd /opt/vagrant/embedded/gems/ 
# chmod -R 0777 <<VERSION>>
# gem install pry --install-dir /opt/vagrant/embedded/gems/<<VERSION>>

require 'pry'

box_path = ENV.fetch('BOX_PATH')
ssh_config_path = ENV.fetch('SSH_CONFIG_PATH')
# pxe_box_path = File.join(box_dir, 'pxe.box')

# TODO: manage these variables with plz not direnv
log_dir = ENV.fetch('SETUP_LOG_DIR')
private_key_path = ENV.fetch('PRIVATE_KEY_PATH')

# TODO: could leverage a metadata file to support automatic upgrading of Vagrant box files
# see https://martincarstenbach.wordpress.com/2020/05/05/versioning-for-your-local-vagrant-boxes-adding-a-new-box/
# and https://martincarstenbach.wordpress.com/2020/05/07/versioning-for-your-local-vagrant-boxes-handling-updates/

Vagrant.configure('2') do |config|
  config.vm.define "provisioner", primary: true do |provisioner|
    provisioner.vm.network "private_network", type: "dhcp", auto_config: true

    provisioner.vm.box = "file://#{box_path}"
    provisioner.vm.synced_folder '.', '/vagrant', disabled: true
    provisioner.vm.network "forwarded_port", guest: 8091, host: 8091
    provisioner.vm.network "forwarded_port", guest: 8092, host: 8092
    # docker registry
    provisioner.vm.network "forwarded_port", guest: 5000, host: 5000

    provisioner.ssh.username = 'ubuntu'
    provisioner.ssh.private_key_path = private_key_path

    provisioner.vm.cloud_init :user_data, content_type: "text/cloud-config", path: "./cloud-init/dev/user-data"

    provisioner.vm.provider 'virtualbox' do |vb|
      vb.gui = false
      vb.memory = "4096"
      vb.cpus = 2

      # Enable promiscious mode on the network adapter to enable bridge networking in the vm
      vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]

      # Setup log file
      vb.customize ["modifyvm", :id, "--uartmode1", "file", File.join(log_dir, "provisioner.log")]
    end

    provisioner.trigger.after [:up, :resume, :reload] do |trigger|
      trigger.info = "Writing out ssh_config file to: #{ssh_config_path}"
      trigger.ruby do |env, machine|
        ssh_config = <<~SSH_CONFIG
Host #{machine.name}
  Port #{machine.ssh_info.fetch(:port)}
  Hostname #{machine.ssh_info.fetch(:host)}
  User #{machine.ssh_info.fetch(:username)}
  IdentityFile #{machine.ssh_info.fetch(:private_key_path).first}
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
        SSH_CONFIG

        FileUtils.mkdir_p(ssh_config_path)
        File.write(File.join(ssh_config_path, machine.name.to_s), ssh_config)
      end
    end
  end

  # config.vm.define "pxe" do |pxe|
  #   # pxe.vm.network "public_network", adapter: 1, auto_config: false, bridge: local_network_bridge_interface
  #   # pxe.vm.network "private_network", type: "dhcp", virtualbox__intnet: "setup-provisioner-network"
  #   pxe.vm.network "private_network", type: "dhcp", auto_config: false

  #   pxe.vm.box = "file://#{pxe_box_path}"
  #   pxe.vm.synced_folder '.', '/vagrant', disabled: true

  #   # we're logging in to Sledgehammer from digitalrebar, not the final deployed machine
  #   pxe.ssh.username = 'root'
  #   pxe.ssh.private_key_path = private_key_path
  #   # pxe.ssh.host = pxe_fqdn

  #   pxe.vm.provider 'virtualbox' do |vb|
  #     vb.gui = false
  #     vb.memory = "4096"
  #     vb.cpus = 2

  #     # Enable promiscious mode on the network adapter to enable bridge networking in the vm
  #     vb.customize ["modifyvm", :id, "--nicpromisc1", "allow-all"]
  #     vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
  #     # vb.customize ['modifyvm', :id, '--nic1', 'natnetwork', '--nat-network1', 'MyNatNetwork']

  #     # Setup log file
  #     vb.customize ["modifyvm", :id, "--uartmode1", "file", File.join(log_dir, "pxe.log")]

  #     # Make sure the network adapter is booted from first
  #     vb.customize ["modifyvm", :id, "--boot1", "net"]
  #     vb.customize ["modifyvm", :id, "--boot2", "disk"]
  #     vb.customize ["modifyvm", :id, "--boot3", "floppy"]

  #     # Make sure the private (second) network adapter is used for pxe booting by giving it priority 1
  #     vb.customize ["modifyvm", :id, "--nicbootprio1", "4"]
  #     vb.customize ["modifyvm", :id, "--nicbootprio2", "1"]
  #   end
  # end
end
