apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ciliumnetworkpolicy-allow-to-root-ingress.yaml
  - clustercleanuppolicy-orphaned-vcluster-secrets.yaml
  - clusterpolicy-enigma-cluster-registration.yaml
  - clusterpolicy-vcluster-registration.yaml
  - clusterrole-kyverno-cleanup-secrets.yaml
  - namespace-setup-argocd-secrets.yaml
  - serviceaccount-argocd.yaml
