"""Fixture factories for fleet-mcp tests

This module provides two types of fixtures:

1. Factory functions (legacy): create_workspace(), create_template(), etc.
   - Programmatic fixture creation with customizable parameters
   - Used by existing tests

2. Manual fixtures: from tests.fixtures import manual
   - Hand-written fixtures for edge cases and error responses
   - Use: manual.make_workspace_error_404()

3. Generated fixtures: from tests.fixtures import generated
   - Auto-generated from real Coder API responses
   - Use: generated.make_workspace_real()
   - Generated by: scripts/generate_factories.py
"""

from . import generated, manual
from .agent_factory import create_agent_workspace, create_app, create_build
from .template_factory import (
    create_preset,
    create_rich_parameter,
    create_template,
    create_template_version,
)
from .workspace_factory import create_workspace

__all__ = [
    "create_agent_workspace",
    "create_app",
    "create_build",
    "create_preset",
    "create_rich_parameter",
    "create_template",
    "create_template_version",
    "create_workspace",
    "generated",
    "manual",
]
