"""
Auto-generated fixture factories from recorded HTTP responses.

DO NOT EDIT THIS FILE MANUALLY!
Generated by: scripts/generate_factories.py
Last updated: 2025-11-05T09:11:55.056057

These fixtures are generated from real Coder API responses recorded using
the recording script (scripts/record_fixtures.py).

Usage:
    from tests.fixtures import generated

    # Use in tests
    workspace = generated.make_workspace_real()
    templates = generated.make_list_templates_real()
"""

from typing import Any


def make_list_templates_real() -> list[Any]:
    """List Templates fixture from real Coder API

    Generated from: template_metadata.json
    Endpoint: GET /api/v2/templates
    Status: 200
    Recorded: 2025-01-01T00:00:00Z
    """
    return [
        {
            "id": "test-uuid-002",
            "created_at": "2025-01-01T00:00:00Z",
            "updated_at": "2025-01-01T00:00:00Z",
            "organization_id": "test-uuid-003",
            "organization_name": "coder",
            "organization_display_name": "Coder",
            "organization_icon": "",
            "name": "coder-devcontainer",
            "display_name": "Setup",
            "provisioner": "terraform",
            "active_version_id": "test-uuid-004",
            "active_user_count": 1,
            "build_time_stats": {
                "delete": {"P50": 22883, "P95": 41845},
                "start": {"P50": 20132, "P95": 56869},
                "stop": {"P50": 32133, "P95": 32133},
            },
            "description": "",
            "deprecated": False,
            "deprecation_message": "",
            "icon": "",
            "default_ttl_ms": 0,
            "activity_bump_ms": 3600000,
            "autostop_requirement": {"days_of_week": [], "weeks": 1},
            "autostart_requirement": {
                "days_of_week": [
                    "monday",
                    "tuesday",
                    "wednesday",
                    "thursday",
                    "friday",
                    "saturday",
                    "sunday",
                ]
            },
            "created_by_id": "test-uuid-005",
            "created_by_name": "mvgijssel",
            "allow_user_autostart": True,
            "allow_user_autostop": True,
            "allow_user_cancel_workspace_jobs": False,
            "failure_ttl_ms": 0,
            "time_til_dormant_ms": 0,
            "time_til_dormant_autodelete_ms": 0,
            "require_active_version": False,
            "max_port_share_level": "public",
            "cors_behavior": "simple",
            "use_classic_parameter_flow": False,
        },
        {
            "id": "test-uuid-006",
            "created_at": "2025-01-01T00:00:00Z",
            "updated_at": "2025-01-01T00:00:00Z",
            "organization_id": "test-uuid-003",
            "organization_name": "coder",
            "organization_display_name": "Coder",
            "organization_icon": "",
            "name": "coder-dataone-devcontainer",
            "display_name": "DataOne",
            "provisioner": "terraform",
            "active_version_id": "test-uuid-007",
            "active_user_count": 0,
            "build_time_stats": {
                "delete": {"P50": 43618, "P95": 45170},
                "start": {"P50": 16852, "P95": 18483},
                "stop": {"P50": 25979, "P95": 25979},
            },
            "description": "",
            "deprecated": False,
            "deprecation_message": "",
            "icon": "",
            "default_ttl_ms": 0,
            "activity_bump_ms": 3600000,
            "autostop_requirement": {"days_of_week": [], "weeks": 1},
            "autostart_requirement": {
                "days_of_week": [
                    "monday",
                    "tuesday",
                    "wednesday",
                    "thursday",
                    "friday",
                    "saturday",
                    "sunday",
                ]
            },
            "created_by_id": "test-uuid-005",
            "created_by_name": "mvgijssel",
            "allow_user_autostart": True,
            "allow_user_autostop": True,
            "allow_user_cancel_workspace_jobs": False,
            "failure_ttl_ms": 0,
            "time_til_dormant_ms": 0,
            "time_til_dormant_autodelete_ms": 0,
            "require_active_version": False,
            "max_port_share_level": "public",
            "cors_behavior": "simple",
            "use_classic_parameter_flow": False,
        },
    ]


def make_get_template_version_rich_parameters_real() -> list[Any]:
    """Get Template Version Rich Parameters fixture from real Coder API

    Generated from: template_metadata.json
    Endpoint: GET /api/v2/templateversions/test-uuid-001/rich-parameters
    Status: 200
    Recorded: 2025-01-01T00:00:00Z
    """
    return [
        {
            "name": "AI Prompt",
            "description": "Write a prompt for Claude Code",
            "description_plaintext": "Write a prompt for Claude Code",
            "type": "string",
            "form_type": "input",
            "mutable": True,
            "default_value": "",
            "icon": "",
            "options": [],
            "required": False,
            "ephemeral": False,
        },
        {
            "name": "system_prompt",
            "display_name": "System Prompt",
            "description": "System prompt for the agent with generalized instructions (required - select a preset)",
            "description_plaintext": "System prompt for the agent with generalized instructions (required - select a preset)",
            "type": "string",
            "form_type": "textarea",
            "mutable": False,
            "default_value": "",
            "icon": "",
            "options": [],
            "required": False,
            "ephemeral": False,
        },
    ]


def make_get_template_version_presets_real() -> list[Any]:
    """Get Template Version Presets fixture from real Coder API

    Generated from: template_metadata.json
    Endpoint: GET /api/v2/templateversions/test-uuid-001/presets
    Status: 200
    Recorded: 2025-01-01T00:00:00Z
    """
    return [
        {
            "ID": "test-uuid-003",
            "Name": "Coder",
            "Parameters": [
                {
                    "Name": "system_prompt",
                    "Value": "You are an expert software development assistant specialized in implementing features and fixing bugs.\n\nYour primary focus is on:\n- Writing clean, maintainable, and well-tested code\n- Following established patterns and conventions in the codebase\n- Implementing comprehensive tests (unit, integration, and e2e)\n- Ensuring code quality through linting, formatting, and type checking\n- Documenting complex logic and design decisions\n- Optimizing for performance and scalability when appropriate\n\nWhen approaching tasks:\n1. Analyze the existing codebase structure and patterns\n2. Plan the implementation with clear steps\n3. Write the code following best practices\n4. Add appropriate tests to verify functionality\n5. Validate with linting and formatting tools\n6. Review and refine the implementation\n\nYou are running inside a Coder Workspace and provide status updates to the user via Coder MCP.\nStay on track, feel free to debug, but when the original plan fails, do not choose a different\nroute/architecture without checking with the user first.\n",
                }
            ],
            "Default": True,
            "DesiredPrebuildInstances": 0,
            "Description": "",
            "Icon": "",
        },
        {
            "ID": "test-uuid-004",
            "Name": "Operator",
            "Parameters": [
                {
                    "Name": "system_prompt",
                    "Value": "You are an expert site reliability engineer and incident response specialist.\n\nYour primary focus is on:\n- Rapid diagnostics and troubleshooting of production issues\n- Analyzing logs, metrics, and system behavior to identify root causes\n- Understanding system architecture and dependencies\n- Investigating performance degradations and service disruptions\n- Providing clear, actionable insights for incident resolution\n- Documenting findings and creating postmortem reports when requested\n\nWhen investigating incidents:\n1. Gather relevant context (logs, metrics, recent changes)\n2. Form hypotheses about potential root causes\n3. Test hypotheses systematically using available observability tools\n4. Identify the root cause and contributing factors\n5. Suggest immediate mitigations and long-term preventions\n6. Clearly communicate findings and recommendations\n\nYou are running inside a Coder Workspace and provide status updates to the user via Coder MCP.\nFocus on quick information gathering and analysis. Ask clarifying questions when the scope of\ninvestigation is unclear. Prioritize understanding what happened over implementing fixes unless\nexplicitly asked to implement solutions.\n",
                }
            ],
            "Default": False,
            "DesiredPrebuildInstances": 0,
            "Description": "",
            "Icon": "",
        },
        {
            "ID": "test-uuid-005",
            "Name": "Researcher",
            "Parameters": [
                {
                    "Name": "system_prompt",
                    "Value": "You are an expert research analyst specialized in comprehensive investigation and deep analysis.\n\nYour primary focus is on:\n- Conducting thorough, multi-layered research on complex topics\n- Synthesizing information from multiple sources and perspectives\n- Identifying patterns, connections, and underlying principles\n- Exploring edge cases, alternative approaches, and related concepts\n- Building comprehensive mental models of systems and domains\n- Evaluating claims with critical thinking and evidence-based reasoning\n- Documenting findings with detailed analysis and supporting evidence\n\nWhen conducting research:\n1. Define clear research questions and objectives\n2. Systematically explore the codebase, documentation, and related resources\n3. Follow tangential connections that may reveal deeper insights\n4. Cross-reference findings across multiple sources for validation\n5. Analyze not just what exists, but why it exists and what alternatives were considered\n6. Document your research process and reasoning chain\n7. Synthesize findings into coherent, comprehensive reports\n8. Identify gaps in understanding and areas requiring further investigation\n\nResearch principles:\n- Prioritize depth and accuracy over speed\n- Be thorough but focused - avoid rabbit holes that don't serve the research goal\n- Question assumptions and look for counter-evidence\n- Trace the evolution of code, decisions, and architecture over time\n- Consider multiple perspectives and interpretations\n- Make connections between seemingly unrelated concepts\n\nYou are running inside a Coder Workspace and provide status updates to the user via Coder MCP.\nTake your time to explore thoroughly. When you discover something interesting, follow the thread\nto its logical conclusion. Ask clarifying questions to ensure your research aligns with user needs.\nFocus on understanding over implementation - only suggest or implement solutions when explicitly\nrequested.\n",
                }
            ],
            "Default": False,
            "DesiredPrebuildInstances": 0,
            "Description": "",
            "Icon": "",
        },
    ]
