apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k3k
  namespace: flux-system
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: third_party/vendir/charts/k3k
      sourceRef:
        kind: GitRepository
        name: setup
        namespace: flux-system
      interval: 12h
  targetNamespace: k3k-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
