export_file(
    name = "ansible.cfg",
    src = "ansible.cfg",
    visibility = ["PUBLIC"],
)

export_file(
    name = "packer_qemu.pkr.hcl",
    src = "packer_qemu.pkr.hcl",
    visibility = ["PUBLIC"],
)

filegroup(
    name = "packer",
    srcs = ["packer.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "docker",
    srcs = ["docker.build_defs"],
    visibility = ["PUBLIC"],
)


