apiVersion: v1
kind: Secret
metadata:
  name: backblaze-credentials
  namespace: relay
stringData:
  bucket: s3-docs-infra-prod
  key_id: placeholder
  application_key: placeholder
  # Cross-cluster access via shared serviceCIDR (10.96.0.0/16)
  # This is the ClusterIP of aws-sigv4-proxy in secrets cluster
  endpoint: http://10.96.80.126
  region: placeholder
