apiVersion: v2
name: openbao
description: OpenBao single-node raft secret store
version: 1.0.0
appVersion: v2.5.5
dependencies:
  - name: openbao
    version: 0.28.4
    repository: file://../../../third_party/vendir/charts/openbao
