filegroup(
    name = "id_rsa",
    srcs = ["id_rsa.development"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "id_rsa_pub",
    srcs = ["id_rsa.development.pub"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "rackn-license",
    srcs = ["rackn-license.json"],
    visibility = ["PUBLIC"],
)