#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo "ADDING STRETCH SECURITY LIST FOR OPENJDK JAVA 8"

echo "deb http://security.debian.org/debian-security stretch/updates main" > /etc/apt/sources.list.d/security_stretch.list