#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

echo "INSTALLING RAZOR SERVER"

# TODO: the certificate is currently expired?
wget --no-check-certificate -O razor-server.deb https://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb

dpkg -i razor-server.deb

rm razor-server.deb
