apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vgijssel/setup
    targetRevision: mg/feat/deploy-secrets-proxy
    path: apps/secrets-proxy
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
