apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vgijssel/setup
    targetRevision: HEAD
    path: apps/argocd-infra
  destination:
    name: enigma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
